apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: go-app-deployment
spec:
  selector:
    matchLabels:
      app: go-app
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: owahed1/go-lang-app:0.0.2 # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8000 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: go-app-service
spec:
  selector:
    app: go-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8000 
  type: LoadBalancer # type of the service.
